### ISSUE TITLE
column text is not unique

### ISSUE THREAD

**Issue by edwardinubuntu** [chamkank/flask-chatterbot#6]
I deployed to heroku with Procfile: 

`web:gunicorn app:chamkank `

And just change this example from app.py to chamkank.py

After build success, start to launch gunicorn got following issues.

sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) column text is not unique [SQL: 'INSERT INTO "StatementTable" (text, extra_data) VALUES (?, ?)'] [parameters: ('Artificial Intelligence is the branch of engineering and science devoted to constructing machines that think.', <memory at 0x7f30d0599048>)]

**Comment by edwardinubuntu** [comment]
I think it's sql adapter problem with gnicorn, in my localhost it doing great. And after I change adapter from sqlite to mogodb: `storage_adapter='chatterbot.storage.MongoDatabaseAdapter'` all work fine on heroku.

**Comment by chamkank** [comment]
Thanks for reporting this, from [this article](https://devcenter.heroku.com/articles/sqlite3) it seems that Heroku doesn't support SQLite because of their file system, but does support PostgreSQL.

I'm glad MongoDB works for you, I'll make a note in the README to switch to use the MongoDatabaseAdapter if deploying to Heroku (since SQLite works fine on other hosts like AWS and PythonAnywhere).

**Comment by chamkank** [comment]
Done, see [README](https://github.com/chamkank/flask-chatterbot/blob/master/README.md). Thanks again, let me know if there's anything else you have trouble with on Heroku.

**Comment by edwardinubuntu** [comment]
Thank you so much.
